In [16]:
import duckdb


con = duckdb.connect("../blood_data.duckdb")

In [17]:
df = con.execute("select * from historical").df()

df.head()

,inst_code,visit_date,previous_visit,donation_type,donation_location,classification_id,blood_group
0,11-14010001,2006-01-01,1800-08-10,1,M,C,B
1,11-02030085,2006-01-01,2005-12-18,1,U,C,B
2,11-02030085,2006-01-01,2005-06-30,1,U,C,A
3,11-14010001,2006-01-01,1800-08-10,1,M,C,O
4,11-14010001,2006-01-01,1800-08-10,1,M,C,O

In [30]:
query = "select distinct blood_group from historical"

result = con.sql(query).df()
print(result)

print("\n")

query = "select distinct donation_location from historical order by donation_location"

result = con.sql(query).df()
print(result)
print("\n")
query = "select distinct classification_id from historical order by classification_id"

result = con.sql(query).df()
print(result)

print("\n")
query = "select distinct donation_type from historical order by donation_type"

result = con.sql(query).df()
print(result)

  blood_group
0           B
1           A
2           O
3           U
4           N
5          AB


  donation_location
0                 C
1                 M
2                 U


  classification_id
0                 A
1                 C
2                 F
3                 P
4                 S
5                 U


   donation_type
0             -1
1              1
2              2
3              3
4              4
5              5
6              7

In [37]:
query = "SUMMARIZE historical"

result = con.execute(query).df()
result

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,inst_code,VARCHAR,11-01010011,11-14010001,27,None,None,None,None,None,9331995,0.0
1,visit_date,DATE,2006-01-01,2025-10-29,6916,2017-01-17 18:45:41.273393,None,2012-09-02,2017-05-18,2021-10-15,9331995,0.0
2,previous_visit,DATE,1800-08-10,2025-10-15,8968,1947-10-27 08:23:12.362855,None,1800-08-10,2012-07-02,2018-12-22,9331995,0.0
3,donation_type,SMALLINT,-1,7,7,1.0424475152419177,0.3564614593994486,1,1,1,9331995,0.0
4,donation_location,VARCHAR,C,U,3,None,None,None,None,None,9331995,0.0
5,classification_id,VARCHAR,A,U,5,None,None,None,None,None,9331995,0.0
6,blood_group,VARCHAR,A,U,6,None,None,None,None,None,9331995,0.0

  classification_id
0                 A
1                 C
2                 F
3                 P
4                 S
5                 U

In [19]:
query = "select blood_group,count(blood_group) from historical where YEAR(visit_date) = 2025 group by blood_group"

result = con.sql(query).df()
result

  blood_group  count(blood_group)
0          AB               27843
1           N                  18
2           B              133969
3           A              122435
4           O              212192
5           U                   4

In [15]:
con.close()