In [16]:
import duckdb


con = duckdb.connect("../blood_data.duckdb")

In [17]:
df = con.execute("select * from historical").df()

df.head()

,inst_code,visit_date,previous_visit,donation_type,donation_location,classification_id,blood_group
0,11-14010001,2006-01-01,1800-08-10,1,M,C,B
1,11-02030085,2006-01-01,2005-12-18,1,U,C,B
2,11-02030085,2006-01-01,2005-06-30,1,U,C,A
3,11-14010001,2006-01-01,1800-08-10,1,M,C,O
4,11-14010001,2006-01-01,1800-08-10,1,M,C,O

In [30]:
query = "select distinct blood_group from historical"

result = con.sql(query).df()
print(result)

print("\n")

query = "select distinct donation_location from historical order by donation_location"

result = con.sql(query).df()
print(result)
print("\n")
query = "select distinct classification_id from historical order by classification_id"

result = con.sql(query).df()
print(result)

print("\n")
query = "select distinct donation_type from historical order by donation_type"

result = con.sql(query).df()
print(result)

  blood_group
0           B
1           A
2           O
3           U
4           N
5          AB


  donation_location
0                 C
1                 M
2                 U


  classification_id
0                 A
1                 C
2                 F
3                 P
4                 S
5                 U


   donation_type
0             -1
1              1
2              2
3              3
4              4
5              5
6              7

In [35]:
query = "DESCRIBE historical"

result = con.execute(query).df()
print(result)

         column_name column_type null   key default extra
0          inst_code     VARCHAR  YES  None    None  None
1         visit_date        DATE  YES  None    None  None
2     previous_visit        DATE  YES  None    None  None
3      donation_type    SMALLINT  YES  None    None  None
4  donation_location     VARCHAR  YES  None    None  None
5  classification_id     VARCHAR  YES  None    None  None
6        blood_group     VARCHAR  YES  None    None  None

  classification_id
0                 A
1                 C
2                 F
3                 P
4                 S
5                 U

In [19]:
query = "select blood_group,count(blood_group) from historical where YEAR(visit_date) = 2025 group by blood_group"

result = con.sql(query).df()
result

  blood_group  count(blood_group)
0          AB               27843
1           N                  18
2           B              133969
3           A              122435
4           O              212192
5           U                   4

In [15]:
con.close()